### ISSUE TITLE
[Enhancement] Make input lowercase before processing it

### ISSUE THREAD

**Issue by StefanVDWeide** [jakeboone02/parse-ingredient#5]
## Issue
Currently when passing a string which lists tbsp as a unit of measurement (UOM) but written like `Tbsp.` the library does not recognise it. It's possible other UOMs are affected but I haven't tested this.

## Example
Given the following input string: `1 Tbsp. drained capers`, the output (incorrectly) looks like this:

```json
  {
    "quantity": 1,
    "quantity2": null,
    "unitOfMeasureID": null,
    "unitOfMeasure": null,
    "description": "Tbsp. drained capers",
    "isGroupHeader": false
  },
``` 

## Solution
When converting the input to lowercase the library correctly recognises the UOM.  

Happy to take a stab at fixing this, let me know!

**Comment by jakeboone02** [comment]
Thanks for the bug report! The reason this library doesn't standardize the case before processing is mainly because "T" (tablespoon) is not the same as "t" (teaspoon).

However, I'm not sure any other units have that problem. Therefore we have two ways we can handle the issue you raised: 1) keep the logic the same and add "Tbsp." to the `alternates` list [on line 95](https://github.com/jakeboone02/parse-ingredient/blob/main/src/index.ts#L95), or 2) modify the logic to standardize on case before processing, treating "T"/"t" and any other case-sensitive units as special cases during _pre_processing.

Honestly I just made this library for a web app for my wife I never quite finished, so if you have any desire to fix the issue please feel free to submit a PR. I'll let you choose which way to solve it. Thanks again!

**Comment by StefanVDWeide** [comment]
Ah that makes sense! I'm not from the USA so I'm not too accustomed to imperial units. It seems that adding it to `alternates` list for now makes the most sense. Atleast until that list gets too long and a clever solution is needed.

I'm currently also intending this for a project for my girlfriend and myself so I'll go ahead and submit a PR.

Thanks for putting this together!

**Comment by StefanVDWeide** [comment]
Opened #7 to fix this.
